spring.application.name=RoSys

spring.datasource.url=jdbc:postgresql://db-gis-rosys.postgres.database.azure.com:5432/gis_test
spring.datasource.username=dbuser
spring.datasource.password=dbuser
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect